### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by zhangyang10418** [Applifier/go-xgboost#2]
$ go build
# github.com/Applifier/go-xgboost/core
core/xgbooster.go:65: cannot use &outLen (type *C.ulong) as type *C.bst_ulong in argument to func literal
core/xgbooster.go:113: cannot use C.ulong(len(handles)) (type C.ulong) as type C.bst_ulong in argument to func literal
core/xgdmatrix.go:30: cannot use &count (type *C.ulong) as type *C.bst_ulong in argument to func literal
core/xgdmatrix.go:40: cannot use &count (type *C.ulong) as type *C.bst_ulong in argument to func literal
core/xgdmatrix.go:52: cannot use C.ulong(len(values)) (type C.ulong) as type C.bst_ulong in argument to func literal
core/xgdmatrix.go:60: cannot use C.ulong(len(group)) (type C.ulong) as type C.bst_ulong in argument to func literal
core/xgdmatrix.go:70: cannot use C.ulong(len(values)) (type C.ulong) as type C.bst_ulong in argument to func literal
core/xgdmatrix.go:87: cannot use &outLen (type *C.ulong) as type *C.bst_ulong in argument to func literal
core/xgdmatrix.go:108: cannot use &outLen (type *C.ulong) as type *C.bst_ulong in argument to func literal
core/xgdmatrix.go:132: cannot use C.ulong(nrows) (type C.ulong) as type C.bst_ulong in argument to func literal
core/xgdmatrix.go:132: too many errors

**Comment by orktes** [comment]
Hi!

Thanks for trying go-xgboost out. Could you give a little bit more context into your setup.

What platform are you trying this out?
How did you build/install xgboost into your system?

https://github.com/Applifier/go-xgboost/blob/master/scripts/Dockerfile-xgboost is a good starting point to see if you are missing something or to see the difference between you setup and the one that the library is tested against.

**Comment by orktes** [comment]
Also are made a commit that changes the used type https://github.com/Applifier/go-xgboost/commit/e77b141dc9cf186c800bf3b902e7f533fa9643c7. Can you see if it works for you now.
