### ISSUE TITLE
Currently, build_docker.sh doesn't run if you're in the directory that it is located in

### ISSUE THREAD

**Issue by michaelgao8** [Applifier/go-xgboost#3]
Small thing, but `build_docker.sh` builds the docker containers from `./scripts/DockerfileXXX`. However, running them in that folder means that the `scripts` folder is the local folder. An easy fix would just be to change the scripts to build from `./Dockerfile-XXX`

**Comment by michaelgao8** [comment]
Unsure if this is for easier testing for CI purposes or to actually test code locally

**Comment by orktes** [comment]
Hi! It is mostly used trough make (See Makefile in the root) but fixing the build script to point relative path should be fairly trivial.
